name: Florida-Custom-Build

on:
  workflow_dispatch: # 支持你在 GitHub 网页上手动一键触发编译
  push:
    branches: ["main", "ci"]
    paths:
      - ".github/workflows/build.yml"
      - "patches/**"

# 定义全局变量，方便你以后修改版本和架构
env:
  TARGET_FRIDA_VERSION: "16.2.1"  # 在这里指定你想要编译的兼容 Frida 版本
  BUILD_ARCH: "android-arm64"      # 仅保留你手机需要的 64 位架构，极大缩短构建时间

jobs: 
  check_version:
    runs-on: ubuntu-22.04
    outputs:
      FRIDA_VERSION: ${{ steps.set_version.outputs.FRIDA_VERSION }}
      ALREADY_RELEASE: ${{ steps.checkReleaseVersion.outputs.ALREADY_RELEASE }}
    steps:
      - name: Set Custom Frida Version
        id: set_version
        run: |
          echo "FRIDA_VERSION=${{ env.TARGET_FRIDA_VERSION }}" >> $GITHUB_OUTPUT

      - name: Split Repository Name
        id: split_name
        run: |
          repo_name=${{ github.repository }}
          IFS='/' read -ra repo_parts <<< "$repo_name"
          echo "owner=${repo_parts[0]}" >> $GITHUB_OUTPUT
          echo "repo=${repo_parts[1]}" >> $GITHUB_OUTPUT

      - name: Check release version
        id: checkReleaseVersion
        uses: actions/github-script@v7
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            try {
              const releaseVersion = '${{ env.TARGET_FRIDA_VERSION }}'
              const releaseResponse = await github.rest.repos.getReleaseByTag({
                owner: '${{ steps.split_name.outputs.owner }}',
                repo: '${{ steps.split_name.outputs.repo }}',
                tag: releaseVersion
              });
              const {
                data: { tag_name: ver }
              } = releaseResponse;
              if (ver == '${{ env.TARGET_FRIDA_VERSION }}'){
                if (${{ (github.event_name == 'push' || github.event_name == 'workflow_dispatch') }}){
                  core.setOutput('ALREADY_RELEASE', '2');
                } else {
                  core.setOutput('ALREADY_RELEASE', '1');
                }
              }
              else{
                core.setOutput('ALREADY_RELEASE', '0');
              }
            } catch (e) {
              if(e.message == 'Not Found'){
                core.setOutput('ALREADY_RELEASE', '0');
              }
              else{
                core.setFailed(e.message);
              }
            }
      
      - name: Delete old release
        if: ${{ steps.checkReleaseVersion.outputs.ALREADY_RELEASE == '2' }}
        uses: dev-drprasad/delete-tag-and-release@v1.0.1
        with:
          tag_name: ${{ env.TARGET_FRIDA_VERSION }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          delete_release: true

  create_release:
    needs: check_version
    runs-on: ubuntu-22.04
    if: needs.check_version.outputs.ALREADY_RELEASE != '1'
    steps:
      - uses: softprops/action-gh-release@v2
        id: createRelease
        name: Create Runner Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "${{ needs.check_version.outputs.FRIDA_VERSION }}"
          name: "${{ needs.check_version.outputs.FRIDA_VERSION }}"
          prerelease: false

  android_build:
    runs-on: ubuntu-22.04
    needs: [check_version, create_release]
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: "temurin"
        java-version: "17"

    - name: Setup Android NDK
      id: setup-ndk
      uses: nttld/setup-ndk@v1
      with:
        ndk-version: r29
        local-cache: false
        link-to-sdk: true

    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: install dependencies
      run: |
        sudo apt-get update && DEBIAN_FRONTEND=noninteractive sudo apt-get install build-essential tree ninja-build gcc-multilib g++-multilib lib32stdc++-9-dev flex bison ruby ruby-dev python3-requests python3-setuptools python3-dev python3-pip libc6-dev libc6-dev-i386 -y
        sudo gem install fpm -v 1.11.0 --no-document
        python3 -m pip install lief

    - name: build frida for Android
      shell: bash
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        
        export ANDROID_NDK_ROOT=${{ steps.setup-ndk.outputs.ndk-path }}
        echo "ANDROID_NDK_ROOT=$ANDROID_NDK_ROOT"
        
        # 1. 深度克隆指定版本的 Frida 并自动初始化子模块（防止补丁版本冲突）
        git clone --branch ${{ env.TARGET_FRIDA_VERSION }} --depth 1 https://github.com/frida/frida
        cd frida
        git submodule update --init --recursive --depth 1
        
        # 2. 依次打入项目中预设的补丁
        for path in ../patches/*
        do
          name=$(basename $path)
          real=$(realpath $path)
          echo "Apply patches in $real to frida/subprojects/$name"
          cd subprojects/$name
          git am ../../../patches/$name/*.patch
          cd ../..
        done
        cd ..
        
        # 3. 仅编译自定义架构（如 android-arm64）
        ARCHES="${{ env.BUILD_ARCH }}"
        for ARCH in $ARCHES
        do
          mkdir build-$ARCH
          cd build-$ARCH
          ../frida/configure --host=$ARCH
          make
          cd ..
        done
    
    - name: Split Repository Name
      id: split_name
      run: |
        repo_name=${{ github.repository }}
        IFS='/' read -ra repo_parts <<< "$repo_name"
        echo "owner=${repo_parts[0]}" >> $GITHUB_OUTPUT
        echo "repo=${repo_parts[1]}" >> $GITHUB_OUTPUT

    - name: Check release version
      id: checkReleaseVersion
      uses: actions/github-script@v7
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          try {
            const releaseVersion = '${{ needs.check_version.outputs.FRIDA_VERSION }}'
            const releaseResponse = await github.rest.repos.getReleaseByTag({
              owner: '${{ steps.split_name.outputs.owner }}',
              repo: '${{ steps.split_name.outputs.repo }}',
              tag: releaseVersion
            })
            const {
              data: { id: releaseId, html_url: htmlUrl, upload_url: uploadUrl }
            } = releaseResponse;
            core.setOutput('id', releaseId);
            core.setOutput('html_url', htmlUrl);
            core.setOutput('upload_url', uploadUrl);
            core.setOutput('version', releaseVersion);
          } catch (e) {
            core.setFailed(e.message);
          }

    - name: package build result for Android
      shell: bash
      run: |
        # 仅对打包了的 arm64 目标进行压缩
        gzip build-android-arm64/subprojects/frida-core/server/frida-server
        gzip build-android-arm64/subprojects/frida-core/inject/frida-inject
        gzip build-android-arm64/subprojects/frida-core/lib/gadget/frida-gadget.so
        gzip build-android-arm64/subprojects/frida-gum/bindings/gumjs/libfrida-gumjs-1.0.a

    - name: Upload android arm64 frida-server for Florida
      uses: softprops/action-gh-release@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: "${{ needs.check_version.outputs.FRIDA_VERSION }}"
        files: '${{ github.workspace }}/build-android-arm64/subprojects/frida-core/server/frida-server.gz'

    - name: Upload android arm64 frida-inject for Florida
      uses: softprops/action-gh-release@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: "${{ needs.check_version.outputs.FRIDA_VERSION }}"
        files: '${{ github.workspace }}/build-android-arm64/subprojects/frida-core/inject/frida-inject.gz'
    
    - name: Upload android arm64 frida-gadget for Florida
      uses: softprops/action-gh-release@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: "${{ needs.check_version.outputs.FRIDA_VERSION }}"
        files: '${{ github.workspace }}/build-android-arm64/subprojects/frida-core/lib/gadget/frida-gadget.so.gz'
     
    - name: Upload android arm64 frida-gumjs for Florida
      uses: softprops/action-gh-release@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: "${{ needs.check_version.outputs.FRIDA_VERSION }}"
        files: '${{ github.workspace }}/build-android-arm64/subprojects/frida-gum/bindings/gumjs/libfrida-gumjs-1.0.a.gz'
